In [1]:
import pandas as pd # Pandas library to manipulate the dataframe 
from datetime import timedelta # datetime library to manage time

C:\Users\emman\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
trips = pd.read_csv('data.csv', dtype = {'store_and_fwd_flag': str}) # Importing the data with Pandas read_csv (), column 6 had mixed types so we converted the column type as object and filled null values as unknown    
trips.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.2,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.2,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.6,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.8,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.0,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0

In [3]:
trips['store_and_fwd_flag'] = trips['store_and_fwd_flag'].fillna('Unknown') # column 6 had mixed types so we converted the column type as object and filled null values as unknown

# 1) Extract all trips with trip_distance larger than 50

In [4]:
dfifty = trips[trips['trip_distance'] > 50] # from the column 'trip_distance' we obtain all the rows with distance larger than 50
dfifty

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
23842,2.0,2020-01-01 01:53:07,2020-01-01 03:54:41,1.0,52.30,5.0,N,262,265,1.0,300.00,0.00,0.0,61.78,6.12,0.3,370.70,2.5
39013,2.0,2020-01-01 02:05:07,2020-01-01 03:03:10,1.0,51.23,5.0,N,264,264,1.0,329.00,0.00,0.5,100.78,6.12,0.3,436.70,0.0
41620,1.0,2020-01-01 03:05:54,2020-01-01 04:16:26,1.0,53.80,5.0,N,132,265,1.0,250.00,0.00,0.0,53.35,16.62,0.3,320.27,0.0
58262,2.0,2020-01-01 05:36:12,2020-01-01 06:40:06,1.0,55.23,5.0,N,132,265,2.0,170.00,0.00,0.5,0.00,18.26,0.3,189.06,0.0
63024,2.0,2020-01-01 07:40:30,2020-01-01 08:40:01,1.0,54.19,5.0,N,132,265,1.0,230.00,0.00,0.0,0.00,12.24,0.3,242.54,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6326169,2.0,2020-01-31 22:47:26,2020-01-31 23:49:14,1.0,51.83,5.0,N,132,265,1.0,220.00,0.00,0.5,48.96,23.99,0.3,293.75,0.0
6331181,2.0,2020-01-31 23:45:36,2020-02-01 01:00:25,5.0,57.99,4.0,N,107,265,1.0,245.00,0.50,0.5,38.24,6.12,0.3,293.16,2.5
6333801,2.0,2020-01-31 23:24:16,2020-02-01 01:32:56,1.0,52.97,4.0,N,264,265,1.0,227.00,0.50,0.5,46.16,0.00,0.3,276.96,2.5
6397132,NaN,2020-01-28 11:54:00,2020-01-28 19:35:00,NaN,60.36,NaN,Unknown,17,61,NaN,12.04,0.00,0.5,0.00,12.24,0.3,25.08,0.0
6398446,NaN,2020-01-28 07:37:00,2020-01-28 08:42:00,NaN,210240.07,NaN,Unknown,76,231,NaN,37.77,2.75,0.5,0.00,0.00,0.3,41.32,0.0

# 2) Extract all trips where payment_type is missing

In [5]:
trips[trips['payment_type'].isna()].head() # by using the pandas function .isna() we detect missing values in the column 'payment_type'

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,Unknown,136,232,NaN,51.05,2.75,0.5,0.0,0.0,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,Unknown,121,9,NaN,27.06,2.75,0.0,0.0,0.0,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,Unknown,197,216,NaN,24.36,2.75,0.5,0.0,0.0,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,Unknown,262,236,NaN,26.08,2.75,0.5,0.0,0.0,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,Unknown,45,142,NaN,25.28,2.75,0.5,0.0,0.0,0.3,28.83,0.0

# 3) For each (PULocationID, DOLocationID) pair, determine the number of trips

In [6]:
# we group by 'PULocationID', 'DOLocationID' using the function 'groupby' and the function .size() to obtain the number of trips for each group
# .reset_index(name = '') resets the index of the dataframe and names the new created column.
trips.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name = 'Number of trips')

       PULocationID  DOLocationID  Number of trips
0                 1             1              638
1                 1            50                1
2                 1            68                1
3                 1           138                2
4                 1           140                1
...             ...           ...              ...
31272           265           259                2
31273           265           261                1
31274           265           263                4
31275           265           264              317
31276           265           265             2508

[31277 rows x 3 columns]

# 4) Save all rows with missing VendorID, passenger_count, store_and_fwd_flag, payment_type in a new dataframe called bad, and remove those rows from the original dataframe.

In [7]:
# we use .isnull() and .any(axis = 1)(any row that satifies the condition) to create the dataframe with all trips having null values in the specified columns indicated
nullValue = trips[trips[['VendorID', 'passenger_count', 'store_and_fwd_flag', 'payment_type']].isnull().any(axis=1)]
nullValue

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,Unknown,136,232,NaN,51.05,2.75,0.5,0.0,0.00,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,Unknown,121,9,NaN,27.06,2.75,0.0,0.0,0.00,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,Unknown,197,216,NaN,24.36,2.75,0.5,0.0,0.00,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,Unknown,262,236,NaN,26.08,2.75,0.5,0.0,0.00,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,Unknown,45,142,NaN,25.28,2.75,0.5,0.0,0.00,0.3,28.83,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,Unknown,237,234,NaN,17.59,2.75,0.5,0.0,0.00,0.3,21.14,0.0
6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,Unknown,259,45,NaN,46.67,2.75,0.5,0.0,12.24,0.3,62.46,0.0
6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,Unknown,137,169,NaN,48.85,2.75,0.0,0.0,0.00,0.3,51.90,0.0
6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,Unknown,50,42,NaN,27.17,2.75,0.0,0.0,0.00,0.3,30.22,0.0
6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,Unknown,179,205,NaN,54.56,2.75,0.5,0.0,0.00,0.3,58.11,0.0

In [8]:
# with the function .index we obtain the 'bad' rows index  and delete them from the original dataframe
trips = trips.drop(nullValue.index)
trips

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,1.0,2.10,1.0,N,163,246,1.0,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,1.0,2.13,1.0,N,164,79,1.0,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5
6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,1.0,2.55,1.0,N,79,68,1.0,12.5,0.5,0.5,3.26,0.0,0.3,19.56,2.5
6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,1.0,1.61,1.0,N,100,142,2.0,8.5,0.5,0.5,0.00,0.0,0.3,12.30,2.5
6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0

#  5)  Add a duration column storing how long each trip has taken (use tpep_pickup_datetime, tpep_dropoff_datetime)

In [9]:
# we substract the 'pickup_datetime' from the 'dropoff_datetime' to know how long each trip has taken
trips['duration'] = pd.to_datetime(trips['tpep_dropoff_datetime']) - pd.to_datetime(trips['tpep_pickup_datetime'])

In [10]:
trips.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.2,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5,0 days 00:04:48
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.2,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5,0 days 00:07:25
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.6,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5,0 days 00:06:11
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.8,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0,0 days 00:04:51
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.0,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0,0 days 00:02:18

# 6) For each pickup location, determine how many trips have started there.

In [11]:
# The same procedure as the 3rd point but grouping bu 'PULocationID' and naming the new created column 'trip_count'
trips.groupby('PULocationID').size().reset_index(name='trip_count') # if we want to count null values aswell

     PULocationID  trip_count
0               1         753
1               2           3
2               3          70
3               4        9902
4               5          39
..            ...         ...
255           261       34229
256           262       85591
257           263      123997
258           264       43779
259           265        3090

[260 rows x 2 columns]

# 7) Cluster the pickup time of the day into 30-minute intervals (e.g. from 02:00 to 02:30)

In [12]:
trips['parsed date'] = pd.to_datetime(trips['tpep_pickup_datetime'])
trips['minutes'] = trips['parsed date'].dt.hour * 60 + trips['parsed date'].dt.minute   #tranform time in minutes
trips['tpep_pickup_datetime_intervals'] = trips['minutes'] // 30      #dividing for 30 to create the slices
trips.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration,parsed date,minutes,tpep_pickup_datetime_intervals
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.2,1.0,N,238,239,1.0,...,0.5,1.47,0.0,0.3,11.27,2.5,0 days 00:04:48,2020-01-01 00:28:15,28,0
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.2,1.0,N,239,238,1.0,...,0.5,1.50,0.0,0.3,12.30,2.5,0 days 00:07:25,2020-01-01 00:35:39,35,1
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.6,1.0,N,238,238,1.0,...,0.5,1.00,0.0,0.3,10.80,2.5,0 days 00:06:11,2020-01-01 00:47:41,47,1
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.8,1.0,N,238,151,1.0,...,0.5,1.36,0.0,0.3,8.16,0.0,0 days 00:04:51,2020-01-01 00:55:23,55,1
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.0,1.0,N,193,193,2.0,...,0.5,0.00,0.0,0.3,4.80,0.0,0 days 00:02:18,2020-01-01 00:01:58,1,0

# 8) For each interval, determine the average number of passengers and the average fare amount.

In [13]:
# we obtain the average number of passengers and the average fare amount by using .mean() and grouping by 'tpep_pickup_datetime_intervals'
interAvg = trips.groupby('tpep_pickup_datetime_intervals')[['passenger_count' , 'fare_amount']].mean().reset_index()
# we rename the columns using .rename() function
interAvg = interAvg.rename(columns={'passenger_count':'Avg_passenger','fare_amount':'Avg_fare_amount'})
interAvg.head()

   tpep_pickup_datetime_intervals  Avg_passenger  Avg_fare_amount
0                               0       1.572848        13.526433
1                               1       1.584345        13.214132
2                               2       1.578933        12.699554
3                               3       1.589182        12.265997
4                               4       1.587479        12.089669

# 9) For each payment type and each interval, determine the average fare amount

In [14]:
# Same procedure as we did previously
tripsAvg = trips.groupby(['payment_type', 'tpep_pickup_datetime_intervals'])['fare_amount'].mean().reset_index(name='avg_fare_amount')
tripsAvg

     payment_type  tpep_pickup_datetime_intervals  avg_fare_amount
0             1.0                               0        13.869142
1             1.0                               1        13.472232
2             1.0                               2        12.824603
3             1.0                               3        12.357974
4             1.0                               4        12.008589
..            ...                             ...              ...
188           4.0                              44         1.533326
189           4.0                              45        -0.787090
190           4.0                              46        -0.351277
191           4.0                              47        -2.748432
192           5.0                              35         0.000000

[193 rows x 3 columns]

# 10) For each payment type, determine the interval when the average fare amount is maximum

In [15]:
# By using the previous dataframe, we group by 'payment_type' and get the id (interval) of the maximum 'avg_fare_amount
# In the dataframe result we store the corresponding rows through the ids 
maxid = tripsAvg.groupby('payment_type')['avg_fare_amount'].idxmax()
result = tripsAvg.loc[maxid]
result

     payment_type  tpep_pickup_datetime_intervals  avg_fare_amount
10            1.0                              10        21.256949
58            2.0                              10        14.846814
110           3.0                              14        10.950938
154           4.0                              10         6.634043
192           5.0                              35         0.000000

# 11) For each payment type, determine the interval when the overall ratio between the tip and the fare amounts is maximum

In [16]:
#add column ratio
trips['ratio'] = trips['tip_amount']/trips['fare_amount']

#remove row with nan or inf value
trips_cleaned = trips.dropna(subset=['ratio'])
trips_cleaned = trips_cleaned[~trips_cleaned['ratio'].isin([float('inf'), float('-inf')])]
trips_cleaned[['tip_amount', 'fare_amount', 'ratio']]

         tip_amount  fare_amount     ratio
0              1.47          6.0  0.245000
1              1.50          7.0  0.214286
2              1.00          6.0  0.166667
3              1.36          5.5  0.247273
4              0.00          3.5  0.000000
...             ...          ...       ...
6339561        4.26         17.5  0.243429
6339562        2.96         11.0  0.269091
6339563        3.36         13.0  0.258462
6339564        3.26         12.5  0.260800
6339565        0.00          8.5  0.000000

[6336826 rows x 3 columns]

In [17]:
#for each payment_type and intervals i found the max ratio
max_ratio = trips_cleaned.groupby(["payment_type" , "tpep_pickup_datetime_intervals"])["ratio"].mean().reset_index()
#find the interval with max ratio for each payment type
max_ratio = max_ratio.loc[max_ratio.groupby("payment_type")["ratio"].idxmax()]
max_ratio

     payment_type  tpep_pickup_datetime_intervals     ratio
3             1.0                               3  0.503453
66            2.0                              18  0.000051
138           3.0                              42  0.023336
164           4.0                              20  0.007890

# 12) Find the location with the highest average fare amount

In [18]:
# Average fare amount for each PULocation and DOLocation
meanDO = trips.groupby('DOLocationID')['fare_amount'].mean()
meanPU = trips.groupby('PULocationID')['fare_amount'].mean()

print(f"For pickup the location with higehest average is: {meanPU.idxmax()} with avg fare {meanPU.max()}")
print(f"For dropoff the location with higehest average is: {meanDO.idxmax()} with avg fare {meanDO.max()}")

if (meanDO.max() > meanPU.max()):
    print(f"The location with the higehest average fare amount is: {meanDO.idxmax()}")
else:
    print(f"The location with the higehest average fare amount is: {meanPU.idxmax()}")

For pickup the location with higehest average is: 204 with avg fare 107.0
For dropoff the location with higehest average is: 44 with avg fare 86.77377049180328
The location with the higehest average fare amount is: 204

# 13) Build a new dataframe (called common) where, for each pickup location we keep all trips to the 5 most common destinations (i.e. each pickup location can have different common destinations).

In [19]:
#find for each cople (PULocationID, DOLocationID) the number of trip made
counter = trips.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name='count').sort_values(by=['PULocationID','count'], ascending=[True, False])
counter

       PULocationID  DOLocationID  count
0                 1             1    636
8                 1           264    105
9                 1           265      4
3                 1           138      2
1                 1            50      1
...             ...           ...    ...
26445           265           241      1
26446           265           243      1
26449           265           248      1
26451           265           259      1
26452           265           261      1

[26456 rows x 3 columns]

In [20]:
# take for each PULocationID (groupby) the top 5 destination (head(5))
top_destinations = counter.groupby('PULocationID').head(5)
top_destinations.dropna()

       PULocationID  DOLocationID  count
0                 1             1    636
8                 1           264    105
9                 1           265      4
3                 1           138      2
1                 1            50      1
...             ...           ...    ...
26455           265           265   2496
26454           265           264    317
26357           265             1     76
26370           265            48     18
26399           265           132      8

[1260 rows x 3 columns]

In [21]:
# Merge with original dataset to get the trips that has 'PULocationID' and 'DOLocationID' in the list of the top 5
common = trips.merge(top_destinations[['PULocationID', 'DOLocationID']], on=['PULocationID', 'DOLocationID'])
common

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration,parsed date,minutes,tpep_pickup_datetime_intervals,ratio
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,...,1.47,0.00,0.3,11.27,2.5,0 days 00:04:48,2020-01-01 00:28:15,28,0,0.245000
1,2.0,2020-01-01 00:24:22,2020-01-01 00:25:54,1.0,0.56,1.0,N,238,239,1.0,...,1.70,0.00,0.3,9.00,2.5,0 days 00:01:32,2020-01-01 00:24:22,24,0,0.485714
2,2.0,2020-01-01 00:46:46,2020-01-01 00:49:17,1.0,0.62,1.0,N,238,239,1.0,...,1.00,0.00,0.3,9.30,2.5,0 days 00:02:31,2020-01-01 00:46:46,46,1,0.222222
3,1.0,2020-01-01 00:17:53,2020-01-01 00:22:47,1.0,0.80,1.0,Y,238,239,1.0,...,1.85,0.00,0.3,11.15,2.5,0 days 00:04:54,2020-01-01 00:17:53,17,0,0.336364
4,2.0,2020-01-01 00:49:45,2020-01-01 00:54:12,1.0,0.86,1.0,N,238,239,1.0,...,1.86,0.00,0.3,11.16,2.5,0 days 00:04:27,2020-01-01 00:49:45,49,1,0.338182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956034,2.0,2020-01-31 12:33:49,2020-01-31 12:59:52,1.0,9.59,1.0,N,109,5,1.0,...,0.00,0.00,0.3,30.80,0.0,0 days 00:26:03,2020-01-31 12:33:49,753,25,0.000000
1956035,1.0,2020-01-31 14:20:50,2020-01-31 15:13:20,1.0,0.00,1.0,N,46,61,1.0,...,0.00,6.12,0.3,56.12,0.0,0 days 00:52:30,2020-01-31 14:20:50,860,28,0.000000
1956036,1.0,2020-01-31 19:13:35,2020-01-31 19:25:46,1.0,3.50,1.0,N,57,95,1.0,...,2.95,0.00,0.3,17.75,0.0,0 days 00:12:11,2020-01-31 19:13:35,1153,38,0.226923
1956037,2.0,2020-01-31 19:39:19,2020-01-31 19:39:28,2.0,0.11,5.0,N,204,204,1.0,...,0.00,0.00,0.3,107.80,0.0,0 days 00:00:09,2020-01-31 19:39:19,1179,39,0.000000
1956038,2.0,2020-01-31 20:16:10,2020-01-31 20:20:15,1.0,0.72,1.0,N,73,9,1.0,...,0.00,0.00,0.3,6.30,0.0,0 days 00:04:05,2020-01-31 20:16:10,1216,40,0.000000

# 14) On the common dataframe, for each payment type and each interval, determine the average fare amount

In [22]:
# As done previously, we use the groupby function with the mean() function and name the newly created column as 'com_avg_fare'
commonAvg = common.groupby(['payment_type', 'tpep_pickup_datetime_intervals'])['fare_amount'].mean().reset_index(name='com_avg_fare')
commonAvg

     payment_type  tpep_pickup_datetime_intervals  com_avg_fare
0             1.0                               0      8.588957
1             1.0                               1      8.690681
2             1.0                               2      8.496143
3             1.0                               3      8.026808
4             1.0                               4      7.945909
..            ...                             ...           ...
188           4.0                              44      1.300119
189           4.0                              45     -0.563944
190           4.0                              46     -2.568571
191           4.0                              47     -4.409173
192           5.0                              35      0.000000

[193 rows x 3 columns]

# 15) Compute the difference of the average fare amount computed in the previous point with those computed at point 9.

In [23]:
# To compute the difference we merge the two dataframes on 'payment_type' and 'tpep_pickup_datetime_intervals' 
mergeAvg = pd.merge(commonAvg, tripsAvg, on = ['payment_type', 'tpep_pickup_datetime_intervals'], how = 'inner')
# Calculate the difference of the two columns obtained
mergeAvg['diff_avg'] = mergeAvg['com_avg_fare'] - mergeAvg['avg_fare_amount']
mergeAvg

,payment_type,tpep_pickup_datetime_intervals,com_avg_fare,avg_fare_amount,diff_avg
0,1.0,0,8.588957,13.869142,-5.280185
1,1.0,1,8.690681,13.472232,-4.781551
2,1.0,2,8.496143,12.824603,-4.328460
3,1.0,3,8.026808,12.357974,-4.331167
4,1.0,4,7.945909,12.008589,-4.062679
...,...,...,...,...,...
188,4.0,44,1.300119,1.533326,-0.233207
189,4.0,45,-0.563944,-0.787090,0.223146
190,4.0,46,-2.568571,-0.351277,-2.217294
191,4.0,47,-4.409173,-2.748432,-1.660740
192,5.0,35,0.000000,0.000000,0.000000

# 16) Compute the ratio between the differences computed in the previous point and those computed in point 9. Note: you have to compute a ratio for each pair (payment type, interval).

In [24]:
# Using the previous dataframe we compute the ratio column as 'diff_avg' divided by 'avg_fare_amount' for each pair
mergeAvg['ratio'] = mergeAvg['diff_avg'] / mergeAvg['avg_fare_amount']
mergeAvg

,payment_type,tpep_pickup_datetime_intervals,com_avg_fare,avg_fare_amount,diff_avg,ratio
0,1.0,0,8.588957,13.869142,-5.280185,-0.380715
1,1.0,1,8.690681,13.472232,-4.781551,-0.354919
2,1.0,2,8.496143,12.824603,-4.328460,-0.337512
3,1.0,3,8.026808,12.357974,-4.331167,-0.350475
4,1.0,4,7.945909,12.008589,-4.062679,-0.338314
...,...,...,...,...,...,...
188,4.0,44,1.300119,1.533326,-0.233207,-0.152092
189,4.0,45,-0.563944,-0.787090,0.223146,-0.283508
190,4.0,46,-2.568571,-0.351277,-2.217294,6.312096
191,4.0,47,-4.409173,-2.748432,-1.660740,0.604250
192,5.0,35,0.000000,0.000000,0.000000,NaN

# 17) Build chains of trips. Two trips are consecutive in a chain if (a) they have the same VendorID, (b) the pickup location of the second trip  is also the dropoff location of the first trip, (c) the pickup time of the second trip is after the dropoff time of the first trip, and (d) the pickup time of the second trip is at most 2 minutes later than the dropoff time of the first trip.

In [25]:
#keep only the needed columns and only the rows without nan values
reduced = trips[['VendorID', 'PULocationID', 'DOLocationID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime']]
reduced = reduced.dropna()

reduced['tpep_pickup_datetime'] = pd.to_datetime(reduced['tpep_pickup_datetime'])
reduced['tpep_dropoff_datetime'] = pd.to_datetime(reduced['tpep_dropoff_datetime'])

# Order rows by 'vendorID' and 'tpep_pickup_datetime', the preceding rows of a current analyzed trip will have less pickup time
reduced = reduced.sort_values(by=['VendorID', 'tpep_pickup_datetime'], ascending=[True, True])

reduced

,VendorID,PULocationID,DOLocationID,tpep_pickup_datetime,tpep_dropoff_datetime
8483,1.0,68,170,2020-01-01 00:00:00,2020-01-01 00:13:03
3083,1.0,79,162,2020-01-01 00:00:03,2020-01-01 00:13:04
5760,1.0,264,68,2020-01-01 00:00:05,2020-01-01 00:26:30
5050,1.0,75,75,2020-01-01 00:00:07,2020-01-01 00:03:26
2555,1.0,145,179,2020-01-01 00:00:25,2020-01-01 00:05:59
...,...,...,...,...,...
4269480,2.0,236,262,2020-07-10 11:34:11,2020-07-10 11:42:41
4282277,2.0,236,43,2020-07-31 18:50:41,2020-07-31 18:54:12
275044,2.0,142,161,2021-01-02 00:22:00,2021-01-02 00:36:50
275045,2.0,170,148,2021-01-02 00:44:08,2021-01-02 00:58:56
275046,2.0,90,148,2021-01-02 01:12:10,2021-01-02 01:25:01

In [ ]:
import time
#this function allows to find all precedents trips (that match the pre-fixed conditions) of current_trip
def find_valid_trips(reduced, current_trip, i):

    #search the valid trips only in the previous row (only in the rows that have already been analized)
    valid_trips = reduced.iloc[:i]
    #the past trips must certainly have arrived no more than two minutes earlier if we want a match (current_trip['tpep_pickup_datetime'] - timedelta(minutes=2) >= reduced['tpep_dropoff_datetime'])
    #if they arrived first there is no need to keep them in the database because going forward they will certainly not have matches (dataset is sorted by PU time)
    #with loc and with this condition we delete the unusefull rows (the one that has wrong DO time)
    reduced = reduced.loc[current_trip['tpep_pickup_datetime'] - timedelta(minutes=2) >= reduced['tpep_dropoff_datetime'],:]

    #search the trips that meet the conditions
    valid_trips = valid_trips[
    (current_trip['PULocationID'] == valid_trips['DOLocationID']) &
    (current_trip['tpep_pickup_datetime'] > valid_trips['tpep_dropoff_datetime']) &
    ((current_trip['tpep_pickup_datetime'] - valid_trips['tpep_dropoff_datetime']) < timedelta(minutes=2))
    ]

    #extract the indices of these trips
    valid_trip_indices = valid_trips.index.tolist()
    
    return valid_trip_indices


#this function allows to update the dictionary with the trip sequences
def update_chain(chains_dict, valid_trips, current_trip):

    #for each trip identified as preceding the current trip, update the found sequences
    for past_trip in valid_trips:

        # If a valid preceding trip exists, the chain is extended. If not, a new chain is created
        #it means that in the dictionary there is a sequence that ends with that journey
        if past_trip in chains_dict:
            #add current_trip at the existing chain
            chains_dict[past_trip].append(current_trip.name)
            #update the key, key contains the last trip of the chain
            chains_dict[current_trip.name] = chains_dict.pop(past_trip)
            return
        #if past trip isn't already in the chain, a new chain is created
        else:
            #the new chain will contain the index of past trip followed by index of current_trip
            chains_dict[current_trip.name] = [past_trip, current_trip.name]



#start building the dictionary with the chains
# the dictionary contains a sequence of trips and each sequence key is the last trip(id) of the sequence (es. sequence [55, 67] has key = 67)
chains = {}
reduced = reduced.head(100000)

#for each vendorID
for vendor_id in reduced['VendorID'].unique():
    reduced = reduced[reduced['VendorID'] == vendor_id] 

    #analyze each row
    for i in range(len(reduced) - 1):

        #current trip is the row being analyzed
        current_trip = reduced.iloc[i]

        #use the function to find all trips that may precede the current_trip
        valid_trips = find_valid_trips(reduced, current_trip, i)

        #if we have some valid trips we need to update the found sequences
        if len(valid_trips)>0:
            #with this function we update the sequences in the dictionary
            update_chain(chains, valid_trips, current_trip)
                
# No need of dictionary keys anymore 
all_chains = list(chains.values())
print('le sequenze trovate sono: ' , len(all_chains))
print('le sequenze sono: ', all_chains)

In [11]:
from collections import defaultdict

number_to_sequences = defaultdict(list)

#find all the numbers in the sequences
for idx, sequence in enumerate(all_chains):
    for number in sequence:
        number_to_sequences[number].append(idx)

# find the numbers that are in more than one sequence
duplicates = {num: seqs for num, seqs in number_to_sequences.items() if len(seqs) > 1}


if duplicates:
    for number, sequences in duplicates.items():
        print(f"Number {number} is in more than one sequence:  {[all_chains[i] for i in sequences]}")
else:
    print("no duplicates")

Number 2282 is in more than one sequence:  [[2282, 8443], [2282, 3861, 12165, 1769, 6687, 18110, 23922]]
Number 2958 is in more than one sequence:  [[2958, 11339], [2958, 1085, 2603, 1273]]
Number 12247 is in more than one sequence:  [[12247, 4174], [12247, 3009], [12247, 1442], [12247, 12673, 6824]]
Number 11017 is in more than one sequence:  [[11017, 7075], [11017, 5371], [11017, 5006, 502, 8815, 1835], [11017, 6933, 9274, 1844, 559, 27139, 23563, 25506]]
Number 11680 is in more than one sequence:  [[11680, 8970], [11680, 4200, 8717, 2707, 413, 16879, 21224]]
Number 1206 is in more than one sequence:  [[1206, 10652], [1206, 8087], [1206, 8784], [1206, 11028, 11029, 10222, 21392, 13795], [1206, 474, 5843, 1110, 534, 19163, 18462, 16283, 17001]]
Number 615 is in more than one sequence:  [[615, 10504], [615, 11366, 96, 9330, 14491], [615, 2372, 4383, 8230, 19818]]
Number 654 is in more than one sequence:  [[654, 10732], [654, 4308], [654, 12908, 4286], [654, 10832, 5445], [654, 6271, 6125, 3380], [654, 7006, 1367, 6411, 5274, 6412], [654, 9135, 786, 3456, 10289, 17128], [654, 12238, 8113, 2673, 16397, 26327]]
Number 4003 is in more than one sequence:  [[4003, 10986], [4003, 568, 1113, 1740]]
Number 1112 is in more than one sequence:  [[12297, 1112, 228], [1112, 3671], [1112, 3516, 3517, 6528, 7983, 10191, 2675, 21395]]
Number 10582 is in more than one sequence:  [[10582, 7774], [10582, 5939, 5166, 6999], [10582, 4763, 11236, 7855], [10582, 1162, 6215, 20042, 15841, 22050]]
Number 13018 is in more than one sequence:  [[13018, 11766], [13018, 3734, 3213, 7371, 236], [13018, 6117, 8750, 44, 10298, 4202], [13018, 10996, 11580, 611, 3917, 8822, 24943, 16398, 19020]]
Number 409 is in more than one sequence:  [[409, 6548], [409, 2381], [409, 5942, 6901, 8584, 103], [409, 410, 12151, 723, 713, 12448, 10219, 4944, 3405, 21686, 17116], [409, 3173, 2754, 61, 9701, 16093, 14811, 14812, 18732, 15005, 28381]]
Number 5321 is in more than one sequence:  [[5321, 1333], [5321, 9397], [5321, 12303, 11740], [5321, 5000, 5001, 5002], [5321, 2386, 5069, 5972, 5323, 1205], [5321, 5800, 11400, 4629, 19269, 15928], [5321, 9633, 11663, 3812, 711, 24720, 23033]]
Number 2940 is in more than one sequence:  [[2940, 1924], [2940, 6619, 8208], [2940, 5556, 5504], [2940, 2254, 4264], [2940, 7711, 3950, 2133, 6371, 3588]]
Number 1073 is in more than one sequence:  [[1073, 1074], [1073, 966], [1073, 10446, 637], [1073, 7262, 9285, 9035, 17271], [1073, 7707, 10982, 724, 3995, 17780, 22694, 13138, 28042]]
Number 3374 is in more than one sequence:  [[3374, 9945], [3374, 3900, 8521, 4162], [3374, 1799, 1800, 431], [3374, 7866, 8073], [3374, 4381, 8257, 10535, 5529, 1394, 812, 695]]
Number 10039 is in more than one sequence:  [[10039, 8491], [10039, 1732, 12248, 8782, 5802, 6268], [10039, 2466, 6118, 17179]]
Number 2575 is in more than one sequence:  [[2575, 1012], [2575, 11936]]
Number 8858 is in more than one sequence:  [[8858, 1287], [8858, 6702, 4818, 4819, 21230]]
Number 5969 is in more than one sequence:  [[5969, 5040], [5969, 8127, 4655, 11383]]
Number 12217 is in more than one sequence:  [[12217, 535], [12217, 1992, 289, 10352, 10139], [12217, 7424, 9883, 13010, 22757], [12217, 8307, 7418, 11395, 6428, 15577, 27708], [12217, 153, 11277, 2703, 15245, 25005, 33413, 40339]]
Number 6187 is in more than one sequence:  [[9251, 6187, 762], [6187, 2077], [6187, 5240, 2131, 7589, 12915], [6187, 11266, 9007, 3011], [6187, 9992, 11501, 9253, 10678, 4805], [6187, 6720, 2512, 747, 8523, 18690], [6187, 7861, 1831, 26158], [6187, 9252, 101, 448, 12103, 10998, 19293, 19415, 17830, 24817, 21708, 36366, 37841]]
Number 1028 is in more than one sequence:  [[1028, 10905], [1028, 4009, 5970, 10513, 10894, 15766]]
Number 8255 is in more than one sequence:  [[8255, 7354], [8255, 7637], [8255, 8296, 6777]]
Number 5246 is in more than one sequence:  [[5246, 978], [5246, 5247], [5246, 461, 2394, 25961], [5246, 2171, 8256, 17872]]
Number 8483 is in more than one sequence:  [[8483, 11105], [8483, 12479, 9284], [8483, 669, 10947, 2044, 7872], [8483, 3589, 7439, 19216], [8483, 3375, 10092, 11031, 25635, 17257, 24915]]
Number 5089 is in more than one sequence:  [[5089, 6563], [5089, 9703, 11889], [5089, 3480, 12077, 5535, 6929, 6615, 27919, 17923]]
Number 11366 is in more than one sequence:  [[11366, 1834], [11366, 12188], [11366, 3029, 7708], [615, 11366, 96, 9330, 14491], [11366, 7438, 5012, 3834, 123, 18685, 20614], [11366, 7849, 463, 13534, 22484, 28618]]
Number 12238 is in more than one sequence:  [[12238, 8294], [12238, 2054, 7787], [12238, 6426, 9295, 34], [12238, 614, 2445, 1780], [12238, 7523, 1138, 8539], [12238, 12599, 7239, 3792], [12238, 8462, 12818, 10907, 10908], [12238, 11081, 3554, 11681, 8259, 22369], [654, 12238, 8113, 2673, 16397, 26327], [12238, 1947, 7754, 4850, 4851, 16745, 27523, 24079, 24080, 16999, 20263], [12238, 1133, 8666, 22842, 23626], [12238, 817, 4570, 2620, 5761, 2113, 14182, 15009, 39262, 28129, 41145]]
Number 4381 is in more than one sequence:  [[4381, 3419], [3374, 4381, 8257, 10535, 5529, 1394, 812, 695], [4381, 2576, 11256, 2634, 2635]]
Number 2477 is in more than one sequence:  [[2477, 6230], [2477, 10442], [2465, 2477, 9319, 1510, 1729, 9104, 6015, 19783, 24763]]
Number 11568 is in more than one sequence:  [[11568, 6554], [11568, 3403, 12640]]
Number 12479 is in more than one sequence:  [[8483, 12479, 9284], [12479, 120, 1043], [12479, 5616, 20, 5133]]
Number 7156 is in more than one sequence:  [[7156, 1727], [7156, 4273], [7156, 4836, 11459, 2604, 11061, 2830, 18686]]
Number 4339 is in more than one sequence:  [[4339, 582], [4339, 7870, 0, 3590], [4339, 2089, 12714], [4339, 332, 3346, 4309], [4339, 8610, 12499, 8611, 15560]]
Number 5172 is in more than one sequence:  [[5172, 11696], [5172, 3916, 2644], [5172, 569, 591, 571, 3730, 3731]]
Number 1018 is in more than one sequence:  [[1018, 1690], [1018, 1524, 12913], [1018, 10512, 636], [1018, 6359, 2552], [1018, 12874, 7608], [1018, 2393, 946, 328], [1018, 635, 3518, 10639], [1018, 10187, 8460, 3344]]
Number 4817 is in more than one sequence:  [[4817, 9201], [4817, 8346], [4817, 12951, 6695, 5397, 27659, 22612, 23445], [4817, 304, 10199, 4013, 15888, 16129, 13053, 39362, 38638, 34609, 40396, 29103]]
Number 11346 is in more than one sequence:  [[11346, 1423], [11346, 5252, 8001, 7599, 24711], [11346, 4263, 9073, 5145, 2433, 15270]]
Number 7393 is in more than one sequence:  [[7393, 1272], [7393, 8354, 6139], [7393, 2139, 4353, 3004, 12941], [7393, 325, 8344, 7395, 5137, 13748], [7393, 7687, 6612, 6105, 3302, 189, 7426, 8380, 13899, 20451]]
Number 2788 is in more than one sequence:  [[2788, 100], [2788, 4452], [2788, 2941, 4243, 5290], [2788, 2828, 4005, 4280, 11503, 4729, 15136, 17123, 27559]]
Number 1236 is in more than one sequence:  [[1236, 7482, 6387], [1236, 5313, 10912]]
Number 12431 is in more than one sequence:  [[12431, 11317], [12431, 1852, 6661]]
Number 8586 is in more than one sequence:  [[4253, 8586, 10198], [8586, 11044, 11045, 3343], [8586, 810, 11079, 4571, 3765, 13283], [8586, 1954, 3898, 9261, 21125, 19217, 26324, 26325, 17497, 30023, 29424, 36642, 29611, 44656, 44084]]
Number 6341 is in more than one sequence:  [[6341, 9034], [6341, 10845, 6276, 7497, 6346, 18643, 15738, 15739, 15721, 28262, 36833, 31624, 28703, 36406, 49915]]
Number 10552 is in more than one sequence:  [[10552, 9488], [10552, 12007, 757], [10552, 12123, 1051, 11161, 21327, 20695], [10552, 6345, 2840, 4026, 22476, 14906], [10552, 2648, 6738, 588, 9620, 15916, 22210, 21778, 23636, 29311]]
Number 10534 is in more than one sequence:  [[10534, 6141], [10534, 36, 6532, 2240, 9994, 25075, 27108, 13322, 13811, 14269, 40122]]
Number 9135 is in more than one sequence:  [[9135, 12420], [9135, 8371, 3010, 3866], [654, 9135, 786, 3456, 10289, 17128], [9135, 7487, 3293, 25320, 26629, 17258, 21366, 38248, 30997]]
Number 11246 is in more than one sequence:  [[11246, 670], [11246, 11172], [11246, 5725, 2209, 11257], [6952, 12433, 11246, 7775, 3636, 17011]]
Number 8639 is in more than one sequence:  [[8639, 11348], [8639, 12324, 408], [8639, 10243, 13757, 24799, 20745], [8639, 11833, 11824, 9981, 11825, 21346, 21347, 18329, 28952, 28953, 33982, 34811, 42718]]
Number 8558 is in more than one sequence:  [[8558, 11612], [8558, 4628, 9215]]
Number 1732 is in more than one sequence:  [[1732, 12735], [1732, 7700], [1732, 6090, 7173], [10039, 1732, 12248, 8782, 5802, 6268], [1732, 464, 8382, 5506, 1932, 19851, 27952], [1732, 1637, 4764, 231, 13235, 13681, 18227]]
Number 7169 is in more than one sequence:  [[7169, 11662], [11288, 7169, 1355, 4687], [7169, 6953, 7519], [7169, 4060, 782, 7791, 3929, 8372]]
Number 2571 is in more than one sequence:  [[2571, 9005, 2551], [2571, 11672, 5288, 86, 449], [2571, 2013, 4667, 2559, 6056]]
Number 9005 is in more than one sequence:  [[2571, 9005, 2551], [9005, 5314], [9005, 7587, 2722], [9005, 513, 3056, 26168, 19297], [9005, 1345, 1346, 2726, 2727, 22731, 18387]]
Number 12303 is in more than one sequence:  [[5321, 12303, 11740], [12303, 10040, 10824], [12303, 8967, 6190, 4632, 7321], [12303, 7455, 7468, 7158, 16226], [12303, 7756, 10340, 2591, 2898, 10550, 24420, 21619, 19059, 13098, 26042, 14631]]
Number 869 is in more than one sequence:  [[869, 5896, 7512], [869, 2105, 3600], [869, 1872, 9651], [869, 1373, 9721, 3875, 7068]]
Number 5516 is in more than one sequence:  [[5516, 2224], [5516, 501, 6525, 9947, 17479]]
Number 10162 is in more than one sequence:  [[10162, 2483, 10017], [12988, 10162, 5011, 10321, 2705, 4838, 2706, 10427], [10162, 11139, 9315, 7622, 9447, 23786, 20014, 20015, 25639, 14802, 35888]]
Number 9910 is in more than one sequence:  [[9910, 595, 7170], [9910, 11643, 10709]]
Number 595 is in more than one sequence:  [[9910, 595, 7170], [595, 10766, 4858, 8356], [595, 31, 7864, 17329], [595, 3985, 5215, 7177, 2390, 13713, 23264, 14943]]
Number 5797 is in more than one sequence:  [[5797, 285], [5797, 5798, 2633, 326, 960, 1999]]
Number 4097 is in more than one sequence:  [[4097, 7517], [4097, 8962], [4097, 5398, 5399, 10925]]
Number 8000 is in more than one sequence:  [[8000, 12933, 8894], [8000, 8672, 9045], [8000, 530, 1931], [8000, 6193, 3449], [8000, 4879, 2630, 6740]]
Number 12988 is in more than one sequence:  [[12988, 7865, 7959, 8089], [12988, 3508, 951, 2846], [12988, 10162, 5011, 10321, 2705, 4838, 2706, 10427]]
Number 7648 is in more than one sequence:  [[7648, 8888], [7648, 3107, 12668], [7648, 12984, 5045]]
Number 9379 is in more than one sequence:  [[9379, 9380], [9379, 11881], [9379, 11082, 9056, 9046, 21931, 18733, 18365], [9379, 3509, 4786, 11565, 26311, 17729, 24960, 33498], [9379, 4349, 2631, 5684, 14015, 14016, 23085, 40008, 39306], [9379, 2835, 370, 2173, 23074, 24557, 21998, 23912, 32877, 40772]]
Number 9978 is in more than one sequence:  [[9978, 7706], [9978, 5108, 4408], [9978, 5641, 2720], [9978, 7609, 5365, 17106]]
Number 2465 is in more than one sequence:  [[2465, 5047, 1764], [2465, 2477, 9319, 1510, 1729, 9104, 6015, 19783, 24763]]
Number 6367 is in more than one sequence:  [[6367, 7997], [6367, 7308], [6367, 2639, 9314, 8412], [1523, 3758, 6367, 2717, 4520], [6367, 6368, 2374, 4822, 19233, 17332, 28201]]
Number 10545 is in more than one sequence:  [[10545, 6550, 7238], [10545, 5348, 4837, 4006]]
Number 6550 is in more than one sequence:  [[10545, 6550, 7238], [6550, 5332, 12911], [6550, 3632, 9700]]
Number 6271 is in more than one sequence:  [[6271, 6757], [654, 6271, 6125, 3380], [6271, 11901, 12878, 10168, 9619, 16611, 14624, 22758]]
Number 3392 is in more than one sequence:  [[3392, 7172, 8163], [3392, 12926, 596], [3392, 3393, 451, 976, 17122, 20166, 13304, 18557]]
Number 7172 is in more than one sequence:  [[3392, 7172, 8163], [7172, 6214], [7172, 10922], [7172, 167, 11971], [7172, 5135, 1214], [7172, 5948, 6703, 20595], [7172, 11796, 6690, 1445, 33, 18906, 13328]]
Number 2768 is in more than one sequence:  [[2768, 3365], [2768, 7176, 7265], [2768, 6551, 1368, 9004, 25278, 25282, 20565, 25106, 25107]]
Number 5240 is in more than one sequence:  [[5240, 9028], [6187, 5240, 2131, 7589, 12915], [5240, 10286, 1274, 7834, 19972, 17754]]
Number 817 is in more than one sequence:  [[817, 1039], [817, 6984, 11083], [817, 1838, 6407], [12238, 817, 4570, 2620, 5761, 2113, 14182, 15009, 39262, 28129, 41145]]
Number 12036 is in more than one sequence:  [[12036, 8781], [12036, 10706, 8181, 10300, 4558, 27191], [12036, 12877, 4319, 11902, 784, 14956, 23781]]
Number 7036 is in more than one sequence:  [[7036, 5501], [7036, 10823, 8297, 2698, 18662, 14084, 33319, 30964, 29356]]
Number 4474 is in more than one sequence:  [[4474, 6306, 2412], [4474, 7434, 5934], [4474, 1076, 6307, 1925, 4839, 4546, 17201], [4474, 6260, 1161, 17723], [4474, 2238, 4258, 4768, 19119, 23510, 39139]]
Number 6188 is in more than one sequence:  [[6188, 8640], [6188, 6174, 5735, 2130, 825, 19344, 13114], [6188, 12666, 12667, 27624, 16058], [6188, 4863, 5416, 14087], [6188, 10290, 4418, 4975, 12255, 18692]]
Number 6426 is in more than one sequence:  [[6426, 7683], [6426, 1532], [6426, 1859], [12238, 6426, 9295, 34], [6426, 2643, 1535, 6556, 7610, 281], [6426, 4871, 7689, 5532, 24846, 27546], [6426, 9672, 9673, 9715, 21645, 26059, 22373], [6426, 11511, 1663, 1985, 20489, 24093], [6426, 3401, 7303, 27193, 26638, 28768], [6426, 8740, 11126, 13660, 14074, 37429], [6426, 1890, 7854, 10287, 7066, 10679, 16749, 15079, 27224, 18102, 25176, 36037, 32131]]
Number 11673 is in more than one sequence:  [[11673, 43], [11673, 11907]]
Number 786 is in more than one sequence:  [[786, 4662], [786, 3865, 8749], [786, 925, 926, 5249, 1494], [654, 9135, 786, 3456, 10289, 17128]]
Number 6090 is in more than one sequence:  [[1732, 6090, 7173], [6090, 10867, 6846, 21794]]
Number 9182 is in more than one sequence:  [[9182, 12963], [9182, 5380], [9182, 10426, 412], [9182, 7649, 2718]]
Number 3106 is in more than one sequence:  [[3106, 9605, 12573], [3106, 4335, 6311, 2581, 25053], [3106, 6254, 10506, 15877], [3106, 11955, 4407, 7157, 4007, 725, 27485, 18556]]
Number 9605 is in more than one sequence:  [[3106, 9605, 12573], [9605, 8359, 7372, 7396, 15484], [9605, 12645, 12325, 17437, 17407], [9605, 2111, 12421, 8854, 23910, 14650, 36513, 32044, 41505, 33590, 32560]]
Number 590 is in more than one sequence:  [[590, 9837], [590, 9509, 8751], [3670, 6967, 590, 4475, 10923], [590, 5466, 10171, 11368], [590, 9443, 1604, 1825, 26496], [590, 4098, 2749, 1003, 11698, 19349, 21674], [590, 1571, 6194, 19701, 26417, 24928, 22604, 20403, 13586, 37535]]
Number 6216 is in more than one sequence:  [[6216, 1174], [6216, 1629], [6216, 10675, 11866], [6216, 301, 1013], [6216, 1053, 7038]]
Number 5725 is in more than one sequence:  [[5725, 8446], [11246, 5725, 2209, 11257], [5725, 2577, 2210], [5725, 7604, 10717, 5736, 16416], [5725, 4543, 6837, 4245, 4419, 21205, 16671, 23092]]
Number 7587 is in more than one sequence:  [[9005, 7587, 2722], [7587, 10212], [7587, 10224, 4619], [7587, 6620, 4125], [7587, 6410, 11405, 2114, 230, 1965], [7587, 411, 651, 5515, 1874, 27782, 27783]]
Number 10231 is in more than one sequence:  [[10231, 2897], [10231, 10232], [10231, 19, 5124, 1536, 26461]]
Number 1237 is in more than one sequence:  [[1237, 12427], [1237, 5180, 938], [1237, 2671, 10323], [1237, 229, 4268, 1204], [1237, 9879, 720], [1237, 1509, 11937, 2605], [1237, 1099, 1142, 10633], [1237, 994, 4094], [1237, 6852, 8267, 22279], [1237, 5193, 6758, 17438]]
Number 10535 is in more than one sequence:  [[10535, 3061], [3374, 4381, 8257, 10535, 5529, 1394, 812, 695]]
Number 1406 is in more than one sequence:  [[1406, 9329], [1406, 2329, 1407, 9597], [1406, 12437, 26480]]
Number 2317 is in more than one sequence:  [[2317, 3363], [2317, 942, 5799, 19531]]
Number 8381 is in more than one sequence:  [[8381, 5182, 9155], [8381, 12286, 283, 13321, 20077]]
Number 2238 is in more than one sequence:  [[2238, 9191], [2238, 3727, 916, 11648, 13396], [2238, 9100, 1393, 12124, 2837, 24418, 15133], [2238, 5741, 7942, 5511, 19532, 23083, 13799], [2238, 7035, 4473, 9287, 21071, 19130], [4474, 2238, 4258, 4768, 19119, 23510, 39139]]
Number 12251 is in more than one sequence:  [[12251, 3378], [12251, 8173, 4340, 5383], [12251, 9618, 11507], [12251, 8040, 22871, 14081]]
Number 167 is in more than one sequence:  [[7172, 167, 11971], [167, 10742], [167, 10505]]
Number 530 is in more than one sequence:  [[8000, 530, 1931], [530, 4518]]
Number 11443 is in more than one sequence:  [[11443, 1934, 6449], [11443, 11444, 4949, 2879, 7713, 16079], [11443, 7402, 998, 11278, 22942, 25357]]
Number 1934 is in more than one sequence:  [[11443, 1934, 6449], [1934, 4448], [1934, 12731], [1934, 9220, 5173], [1934, 9887, 5966, 7233], [1934, 5351, 4698, 18936], [1934, 66, 11251, 21705, 25837], [1934, 10409, 1693, 25679, 14464, 15624]]
Number 7469 is in more than one sequence:  [[7469, 6004], [7469, 5510, 975, 2796], [7469, 8179, 8436, 16610], [7469, 6934, 7175, 1586, 14899]]
Number 4101 is in more than one sequence:  [[4101, 1678], [4101, 2239, 210], [4101, 11870, 919, 9321]]
Number 11672 is in more than one sequence:  [[11672, 8314, 8315], [11672, 2572, 12990, 2513], [2571, 11672, 5288, 86, 449], [11672, 6992, 4037, 13570, 14867, 16297, 23894]]
Number 4802 is in more than one sequence:  [[4802, 254], [1933, 7860, 4802, 6444, 3364], [4802, 4803, 592]]
Number 10285 is in more than one sequence:  [[10285, 3616, 2789], [3670, 11254, 10285, 4767, 8759]]
Number 3616 is in more than one sequence:  [[10285, 3616, 2789], [3616, 5241], [3616, 445, 292, 15553], [3616, 570, 1981, 1982, 21408, 26152]]
Number 11082 is in more than one sequence:  [[11082, 10645], [11082, 3227], [11082, 4482, 8309, 6054, 11610], [9379, 11082, 9056, 9046, 21931, 18733, 18365], [11082, 3510, 539, 15413, 22258, 30863, 37364, 40328]]
Number 2831 is in more than one sequence:  [[2831, 7399], [2831, 1024], [2831, 8308, 1765]]
Number 57 is in more than one sequence:  [[57, 12329], [57, 10704, 3650], [57, 1334, 1335, 264], [57, 1585, 1023, 12724, 27817]]
Number 3107 is in more than one sequence:  [[7648, 3107, 12668], [3107, 8327], [3107, 12751, 2702, 12983, 22867]]
Number 3670 is in more than one sequence:  [[3670, 5292, 6823, 2424], [3670, 11254, 10285, 4767, 8759], [3670, 6967, 590, 4475, 10923], [3670, 10223, 6423, 4000, 6062, 166], [6976, 3670, 2043, 10583, 6255, 12660]]
Number 5843 is in more than one sequence:  [[5843, 11493], [5843, 12161], [5843, 11575, 3347, 8379], [5843, 2624, 10735, 25322], [1206, 474, 5843, 1110, 534, 19163, 18462, 16283, 17001]]
Number 6366 is in more than one sequence:  [[6366, 9836, 4010, 5911], [6366, 5391, 4022], [6976, 6366, 2411, 5531, 10172, 24421, 20202, 15255, 28849]]
Number 4010 is in more than one sequence:  [[6366, 9836, 4010, 5911], [4010, 4102, 8619], [4010, 7475, 395], [4010, 24, 6370, 5598, 3511, 2993, 18170], [4010, 4011, 446, 17955, 21752]]
Number 6984 is in more than one sequence:  [[817, 6984, 11083], [6984, 11659]]
Number 9342 is in more than one sequence:  [[9342, 2318], [9342, 6386, 11787]]
Number 3403 is in more than one sequence:  [[11568, 3403, 12640], [3403, 9183]]
Number 2585 is in more than one sequence:  [[2585, 719], [2585, 7007, 8609, 15415, 25913, 27360, 40939]]
Number 5583 is in more than one sequence:  [[4024, 5583, 1225, 11460], [5583, 937, 7922]]
Number 712 is in more than one sequence:  [[712, 4972, 4866], [712, 9481, 3973, 11407, 6111]]
Number 4972 is in more than one sequence:  [[712, 4972, 4866], [4972, 2430], [4972, 2524], [4972, 7730, 5734, 11595]]
Number 8127 is in more than one sequence:  [[8127, 4416, 5726], [5969, 8127, 4655, 11383], [8127, 6783, 1980, 2307, 424], [8127, 8128, 5257, 9510, 2801, 458, 27937, 21403, 15666, 28455]]
Number 2438 is in more than one sequence:  [[2438, 934], [2438, 1935], [2438, 11727, 4756], [2438, 1657, 22480, 26217, 24644, 20283], [2438, 5949, 4868, 12441, 2016, 26112, 26113, 22344], [2438, 10167, 5617, 10284, 17260, 25598, 26198]]

In [8]:
reduced.loc[[2282, 8443]]

,VendorID,PULocationID,DOLocationID,tpep_pickup_datetime,tpep_dropoff_datetime
2282,1.0,125,231,2020-01-01 00:04:41,2020-01-01 00:07:49
8443,1.0,231,249,2020-01-01 00:09:26,2020-01-01 00:18:09

In [12]:
reduced.loc[[2282, 3861, 12165, 1769, 6687, 18110, 23922]]

,VendorID,PULocationID,DOLocationID,tpep_pickup_datetime,tpep_dropoff_datetime
2282,1.0,125,231,2020-01-01 00:04:41,2020-01-01 00:07:49
3861,1.0,231,13,2020-01-01 00:09:10,2020-01-01 00:14:28
12165,1.0,13,87,2020-01-01 00:14:44,2020-01-01 00:20:23
1769,1.0,87,164,2020-01-01 00:22:21,2020-01-01 00:46:32
6687,1.0,164,68,2020-01-01 00:46:53,2020-01-01 00:58:30
18110,1.0,68,74,2020-01-01 01:00:13,2020-01-01 01:33:00
23922,1.0,74,145,2020-01-01 01:33:08,2020-01-01 01:57:44

In [ ]:
def whichchain(idis, allchains):
    chn = ''
    for idxis, chayn in enumerate(all_chains):
        if idis in chayn:
            chn += str(idxis) +';'
    return chn
   
for i, row in trips.iterrows():
    idis = row.index()
    chnVal = whichchain(idis, allchains)
    trips['chain'] = chnVal